# Generated by Django 4.2 on 2024-08-14 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_alter_product_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='price_after',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
