# Generated by Django 4.2 on 2024-09-01 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed'), ('R', 'Rejected')], default='P', max_length=20),
        ),
    ]
