# Generated by Django 4.2 on 2024-08-11 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='image',
            field=models.ImageField(default=2, upload_to='store_image'),
            preserve_default=False,
        ),
    ]
