# Generated by Django 4.2 on 2024-08-20 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_bill'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
