# Generated by Django 4.2 on 2024-08-20 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_orderdetail_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetail',
            name='processed',
            field=models.BooleanField(default=False),
        ),
    ]
