# Generated by Django 4.2 on 2024-08-21 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderdetail_processed'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
