# Generated by Django 4.2 on 2024-08-26 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_bill_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderdetail',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('C', 'Confirmed')], default='P', max_length=20),
        ),
    ]
