# Generated by Django 4.2 on 2024-08-26 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
        ('orders', '0007_alter_orderdetail_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='address',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_address', to='customers.address'),
        ),
    ]
